<div class="mx-auto max-w-5xl px-4 py-8"><h1 class="text-3xl font-black">Checkout</h1>
    @error('cart')<div class="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{{ $message }}</div>@enderror
    @if($items->isEmpty())<div class="panel mt-6 p-10 text-center">Keranjang kosong. <a href="{{ route('catalog') }}" class="font-bold text-red-600">Belanja dulu</a>.</div>@else
    <form wire:submit="checkout" class="mt-6 grid gap-6 lg:grid-cols-[1fr_360px]"><div class="space-y-5">
        <section class="panel p-5"><h2 class="font-black">Tujuan pengantaran</h2><label class="label mt-4">Kelas</label><select wire:model="kelas_id" class="input"><option value="">Pilih kelas</option>@foreach($classes as $class)<option value="{{$class->id}}">{{$class->nama}}</option>@endforeach</select>@error('kelas_id')<p class="error">{{$message}}</p>@enderror</section>
        <section class="panel p-5"><h2 class="font-black">Pembayaran</h2><div class="mt-4 grid grid-cols-2 gap-3"><label class="choice"><input wire:model="metode_pembayaran" type="radio" value="cash"> <span><b>Cash</b><small>Bayar ke pengantar</small></span></label><label class="choice"><input wire:model="metode_pembayaran" type="radio" value="qris"> <span><b>QRIS</b><small>Transfer manual</small></span></label></div></section>
        <section class="panel p-5"><label class="label">Catatan (opsional)</label><textarea wire:model="catatan" class="input" rows="3" placeholder="Contoh: tanpa sambal"></textarea></section>
    </div><aside class="panel h-fit p-5"><h2 class="font-black">Ringkasan Pesanan</h2><div class="mt-4 max-h-64 space-y-3 overflow-auto">@foreach($items as $item)<div class="flex justify-between gap-3 text-sm"><span class="line-clamp-1">{{$item->product->nama}} × {{$item->qty}}</span><b class="shrink-0">Rp{{number_format($item->product->harga*$item->qty,0,',','.')}}</b></div>@endforeach</div><hr class="my-4 border-slate-200"><div class="space-y-2 text-sm"><div class="flex justify-between"><span>Subtotal</span><b>Rp{{number_format($subtotal,0,',','.')}}</b></div><div class="flex justify-between"><span>Ongkir</span><b>Rp{{number_format($shipping->nominal,0,',','.')}}</b></div><div class="flex justify-between pt-2 text-lg"><span class="font-black">Total</span><b class="text-red-600">Rp{{number_format($subtotal+$shipping->nominal,0,',','.')}}</b></div></div><button class="btn-primary mt-5 w-full" wire:loading.attr="disabled">Buat Pesanan</button></aside></form>@endif
</div>
